version: "3.9"
services:
  yocto:
    build: .
    container_name: yocto
    tty: true
    volumes:
      - ./work:/home/yocto/work

# Yocto-for-RaspberryPi | MIT License | https://github.com/OOKI-KAWAI/Yocto-for-RaspberryPi/blob/main/LICENSE